version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - ~/.local/bin/uv tool install tox --with tox-uv -p 3.13 --managed-python
    - ~/.local/bin/tox run -e docs --

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: . 

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
