[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.uv]
default-groups = ["docs"]

[tool.uv.dependency-groups]
docs = [{"sphinx"}]

[project]
name = "testProject"
authors = [{name = "Me", email = "Me@real.email"}]
dynamic = ["version", "description"]
