[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[dependency-groups.docs]
dependencies = ["sphinx>=4.0"]
optional = true

[project]
name = "testProject"
authors = [{name = "Me", email = "Me@real.email"}]
dynamic = ["version", "description"]
