import uuid

def main():
    """
    This function prints the random number

    :param: None
    :return: prints the random number generated by random_number
    :rtype: str
    """
    return print(random_number())

def random_number() -> int:
    """
    This function generates a random UUID code.

    :param: None
    :return: uuid.
    :rtype: int
    """
    return uuid.uuid4()

if __name__ == "__main__":
    main()
