from fastapi import FastAPI
from libMain import random_number

__doc__ = """The main program for the api\n"""

__version__ = "0.1.0"

app = FastAPI()

def get_random_number():
    """
    Description of this function
    
    Extended descriptions will appear on automodules but not on the autosummaries (i.e. on the individual pages vs on the summaries page). This string can be as long as you like and you can use '\n' to add paragraphs \n like so
    
    :param None: No input required
    :return: a dictionary with the key "random" and value generated by the random_number function from splice_lib
    :rtype: dictionary 
    """
    return { "random": random_number() }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host= "0.0.0.0", port = 8000)
