"""The main program for the api"""

from fastapi import FastAPI
from libMain import random_number

__version__ = "0.1.0"

app = FastAPI()

def get_random_number():
    """
    Description of this function
    
    Extended descriptions will appear\n
    on automodules but not on the autosummaries\n
    (i.e. on the individual pages vs on the summaries page)

    :param None: No input required
    :return: a dictionary with the key "random" and value generated by the random_number function from splice_lib
    :rtype: dictionary 
    """
    return { "random": random_number() }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host= "0.0.0.0", port = 8000)
