from fastapi import FastAPI
from libMain import random_number

"""
The main program for the api 
"""

__version__ = "0.1.0"

app = FastAPI()

def get_random_number():
    """
    Description of this function

    Does an extended amount of text display properly or is this going to break the automodule? Tune in next time to find out on I Don't Know What I'm Doing (C)
    oooo a new line ('o')

    :param None: No input required
    :return: a dictionary with the key "random" and value generated by the random_number function from splice_lib
    :rtype: dictionary 
    """
    return { "random": random_number() }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host= "0.0.0.0", port = 8000)
