"""
The main program for the api 
"""

from fastapi import FastAPI
from splice_lib import main
from splice_lib.main import random_number

app = FastAPI()

def get_random_number():
    """
    Description of this function

    :param None: No input required
    :return: a dictionary with the key "random" and value generated by the random_number function from splice_lib
    :rtype: dictionary 
    """
    return { "random": random_number() }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host= "0.0.0.0", port = 8000)
